feat: add terranetes preload for AWS config, add missing SA annotations
appvia/wayfinder-defaults pull request #2
Opened 2024-09-06 10:20 UTC by KashifSaadat

2024-09-06 11:07 UTC, lewismarshall approved these changes
Looks good as discussed.

2024-09-06 12:34 UTC, lewismarshall commented
Not sure if this is the culprit but this change didn't pass the e2e on the Wayfinder repo - https://github.com/appvia/wayfinder/actions/runs/10737766939/job/29780202762

So we shouldn't merge just yet...

2024-09-06 13:44 UTC, lewismarshall requested changes

2024-09-06 14:24 UTC, KashifSaadat commented on packages/terranetes-controller.yaml
> -          annotations: {}
whoops! Fixing

2024-09-06 14:37 UTC, lewismarshall commented
So will verify a new cluster comes up with this in my dev environment and then approve 😄

2024-09-06 16:57 UTC, lewismarshall approved these changes

2024-09-25 13:08 UTC, mrsheepuk commented
Closing in favour of a PR we'll make to include these changes and other updates from WF ahead of 2.9.

2024-09-25 13:08 UTC, closed without merging